import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

// `import ... from 'tau'` is a virtual barrel: flat re-export of
// @react-three/fiber plus the four Tauri plugin namespaces. Types live in
// ./tau.d.ts and must stay in sync with TAU_SOURCE below. Bare imports
// inside the source string ('@react-three/fiber', '@tauri-apps/plugin-*')
// resolve through normal node_modules walk-up — `tau create` writes a
// `<project>/node_modules` symlink pointing at `.tau/node_modules` so this
// works from `src/` without any aliasing.
const TAU_VIRTUAL_ID = 'tau';
const TAU_RESOLVED_ID = '\0tau';
const TAU_SOURCE = `// Auto-generated by tau's Vite plugin. Edit .tau/vite.config.js to change.
export * from '@react-three/fiber';
export * as haptics from '@tauri-apps/plugin-haptics';
export * as notification from '@tauri-apps/plugin-notification';
export * as dialog from '@tauri-apps/plugin-dialog';
export * as fs from '@tauri-apps/plugin-fs';
`;

function tauVirtualModule() {
  return {
    name: 'tau:virtual',
    enforce: 'pre',
    resolveId(id) {
      return id === TAU_VIRTUAL_ID ? TAU_RESOLVED_ID : null;
    },
    load(id) {
      return id === TAU_RESOLVED_ID ? TAU_SOURCE : null;
    },
  };
}

export default defineConfig({
  root: resolve(here, '../src'),
  base: './',
  plugins: [react(), tauVirtualModule()],
  cacheDir: resolve(here, 'node_modules/.vite'),
  build: {
    outDir: resolve(here, 'dist'),
    emptyOutDir: true,
    target: 'esnext',
  },
  server: {
    port: 1420,
    strictPort: true,
    host: '127.0.0.1',
    // Vite's HMR client tries to auto-detect the WebSocket URL from
    // window.location. Inside Tauri's webview that often points at the
    // wrong origin (tauri://localhost on macOS, http://tauri.localhost on
    // Windows), and the WS handshake fails silently — page logs "connected"
    // but never receives updates. Pinning the HMR client to the same
    // host:port the dev server binds to fixes it.
    hmr: {
      protocol: 'ws',
      host: '127.0.0.1',
      port: 1420,
    },
    fs: {
      // Vite restricts dev-server file serving to `root` and a few defaults.
      // Since node_modules is outside `root`, opt into serving from the
      // project root + `.tau/` so module bytes can be sent.
      allow: [resolve(here, '..'), here],
    },
    watch: {
      // Vite watches `root` automatically, but the user's source lives at
      // ../src relative to this config — outside the cwd of the spawned
      // Vite process. On Linux this combination (root above cwd) is the
      // classic chokidar case where inotify events don't propagate; the
      // page logs "[vite] connected" but never receives an update. Polling
      // every 100ms is the reliable fix and is cheap for a small source
      // tree. Also covers WSL, Docker, and network FS.
      usePolling: true,
      interval: 100,
      ignored: ['**/node_modules/**', '**/.tau/dist/**', '**/src-tauri/**'],
    },
  },
  clearScreen: false,
});
