import { defineConfig } from 'vite';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { readFileSync } from 'node:fs';

const here = dirname(fileURLToPath(import.meta.url));

// `import ... from 'tau'` is a virtual barrel that re-exports the four
// Tauri plugin namespaces. Types live in ./tau.d.ts. Bare imports inside
// the source string ('@tauri-apps/plugin-*') are resolved by the alias loop
// below because each package is listed in .tau/package.json deps.
const TAU_VIRTUAL_ID = 'tau';
const TAU_RESOLVED_ID = '\0tau';
const TAU_SOURCE = `// Auto-generated by tau's Vite plugin. Edit .tau/vite.config.js to change.
export * as haptics from '@tauri-apps/plugin-haptics';
export * as notification from '@tauri-apps/plugin-notification';
export * as dialog from '@tauri-apps/plugin-dialog';
export * as fs from '@tauri-apps/plugin-fs';
`;

function tauVirtualModule() {
  return {
    name: 'tau:virtual',
    enforce: 'pre',
    resolveId(id) {
      return id === TAU_VIRTUAL_ID ? TAU_RESOLVED_ID : null;
    },
    load(id) {
      return id === TAU_RESOLVED_ID ? TAU_SOURCE : null;
    },
  };
}

// We keep package.json + node_modules inside `.tau/` so the user's project
// root stays clean (just `src/` + `.tau/`). The downside: Vite/Node's
// upward-walking resolver doesn't see `.tau/node_modules` from `src/game.js`.
// To fix that without leaking node_modules into the user's view, we read
// the dependency list from `.tau/package.json` and build explicit aliases
// pointing at `.tau/node_modules/<dep>`. New deps added via `tau add` are
// picked up automatically on next dev/build because we read package.json
// at config-load time.
function depsFromPackageJson() {
  const pkg = JSON.parse(readFileSync(resolve(here, 'package.json'), 'utf8'));
  return Object.keys({ ...pkg.dependencies, ...pkg.devDependencies });
}

const aliases = Object.fromEntries(
  depsFromPackageJson().map((name) => [name, resolve(here, 'node_modules', name)]),
);

export default defineConfig({
  root: resolve(here, '../src'),
  base: './',
  plugins: [tauVirtualModule()],
  resolve: {
    alias: aliases,
    // Vite caches deps it has pre-bundled inside node_modules/.vite. Since
    // our node_modules is in `.tau/`, point its cache there too — otherwise
    // it lands in `src/node_modules/.vite` which we don't want.
    preserveSymlinks: false,
  },
  cacheDir: resolve(here, 'node_modules/.vite'),
  build: {
    outDir: resolve(here, 'dist'),
    emptyOutDir: true,
    target: 'esnext',
  },
  server: {
    port: 1420,
    strictPort: true,
    host: '127.0.0.1',
    // Vite's HMR client tries to auto-detect the WebSocket URL from
    // window.location, which inside a Tauri webview points at the wrong
    // origin (tauri://localhost on macOS, http://tauri.localhost on Windows).
    // The connection fails silently and the webview just sits there. Pinning
    // the HMR client to the same host:port the dev server binds to fixes it.
    hmr: {
      protocol: 'ws',
      host: '127.0.0.1',
      port: 1420,
    },
    fs: {
      // Vite restricts dev-server file serving to `root` and a few defaults.
      // Since node_modules is outside `root`, opt into serving from the
      // project root + `.tau/` so module bytes can be sent.
      allow: [resolve(here, '..'), here],
    },
  },
  clearScreen: false,
});
